#!/usr/bin/env ruby
# frozen_string_literal: true

begin
  require 'bundler/setup'
rescue LoadError
  nil
end

$LOAD_PATH.unshift(File.expand_path('../lib', __dir__))
require 'create_ruby_gem'

exit(CreateRubyGem::CLI.start(ARGV))
